{
  "labels": {
    "created-by: Pedaki team": [
      { "type": "user", "pattern": "vahor" }
    ],
    "area: documentation": [
      "docs/**"
    ],
    "area: site": [
      "apps/web/**"
    ]
  }
}